images:
  dlami-x64:
    platform: "linux"
    arch: "x64"
    owner: "898082745236" # AWS
    name: "Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04)*"
  custom:
    # make sure to enclose owner in quotes, otherwise yaml will interpret it as a number
    owner: "099720109477"
    name: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
    arch: x64
    platform: linux
    preinstall: |
      #!/bin/bash
      touch /tmp/preinstalled

runners:
  preinstall-ok:
    image: ubuntu22-full-x64
    cpu: 2
    family: [c7]
    preinstall: |
      #!/bin/bash
      echo "preinstall ok"
    tags:
      - "tag-custom-key1:tag-custom-value1"
      - "tag-custom-key2-no-value"
  preinstall-ko:
    image: ubuntu22-full-x64
    cpu: 2
    family: [c7]
    preinstall: |
      #!/bin/bash
      echo "preinstall ko"
      exit 1
  gofast:
    cpu: 4
    family: [c7a, c7i]
    image: ubuntu22-full-x64
  gpu-nvidia:
    family: ["g4dn.xlarge"]
    image: dlami-x64
  s3-cache:
    image: ubuntu24-full-x64
    extras: s3-cache
    cpu: 2
    family: [m7a]
